#!/usr/bin/env python3
# Made by:
# Jan Benda             465aae63-030f-11eb-9574-ea7484399335
# Veronika Borková      8f7b6d5d-adcc-41af-9ea0-6744c950079e

import argparse
import os

import torch

import npfl138
npfl138.require_version("2526.8")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Dataset(npfl138.TransformedDataset):
    def transform(self, example):
        # Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        #
        # However, compared to `tagger_we`, keep in the target sequence only the tags
        # starting with "B-" (before remapping them to ids).
        word_ids = torch.tensor(self.dataset.words.string_vocab.indices(example["words"]))
        tag_ids = torch.tensor(self.dataset.tags.string_vocab.indices([tag for tag in example["tags"] if tag.startswith("B-")]))
        #tag_ids = torch.tensor([self.dataset.tags.string_vocab[tag] for tag in example["tags"] if tag.startswith("B-")],dtype=torch.long)
        return word_ids, tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, tag_ids = zip(*batch)
        # Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True, padding_value=0)
        # Process `tag_ids` analogously to `word_ids`.
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True, padding_value=0)
        return word_ids, tag_ids


class Model(npfl138.TrainableModule):
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()

        # Create all needed layers.
        # create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(len(train.words.string_vocab), args.we_dim)

        # Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # and we will sum the outputs of forward and backward directions.
        if args.rnn == "LSTM":
            self._word_rnn = torch.nn.LSTM(
                bidirectional=True, input_size=args.we_dim, hidden_size=args.rnn_dim, batch_first=True)
        elif args.rnn == "GRU":
            self._word_rnn = torch.nn.GRU(
                bidirectional=True, input_size=args.we_dim, hidden_size=args.rnn_dim, batch_first=True)
        else:
            print("Neznama RNN, exit")

        # Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(args.rnn_dim, len(train.tags.string_vocab))
    
    # GOOD
    def forward(self, word_ids: torch.Tensor) -> torch.Tensor:
        # Start by embedding the `word_ids` using the word embedding layer.
        hidden = self._word_embedding(word_ids)

        # Process the embedded words through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        packed = torch.nn.utils.rnn.pack_padded_sequence(hidden, (word_ids != MorphoDataset.PAD).sum(dim=1).cpu(), batch_first=True, enforce_sorted=False)

        # Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed = self._word_rnn(packed)[0]

        # Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)[0]
        hidden = hidden[:, :, :self._word_rnn.hidden_size] + hidden[:, :, self._word_rnn.hidden_size:]

        # Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        hidden = self._output_layer(hidden)
        hidden = hidden.permute(0, 2, 1)

        return hidden

    def compute_loss(self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO: Compute the loss as the negative log-likelihood of the gold data `y_true`.
        # The computation must process the whole batch at once.
        # - Start by computing the log probabilities of the predictions using the `log_softmax` method.
        # - Compute the alphas according to the CTC algorithm.
        # - Then, you need to take the appropriate alpha for every batch example (using the corresponding
        #   lengths of `y_pred` and also `y_true`) and compute the loss from it.
        # - The losses of the individual examples should be divided by the length of the
        #   target sequence (excluding padding; use 1 if the target sequence is empty).
        #   - This is because we want to compute averages per logit; the `torch.nn.CTCLoss` does
        #     exactly the same when `reduction="mean"` (the default) is used.
        # - Finally, return the mean of the resulting losses.
        #
        # Several comments:
        # - You can add numbers represented in log space using `torch.logsumexp`/`torch.logaddexp`.
        # - With a slight abuse of notation, use `MorphoDataset.PAD` as the blank label in the CTC algorithm
        #   because `MorphoDataset.PAD` is never a valid output tag.
        # - During the computation, I use `-1e9` as the representation of negative infinity; using
        #   `-torch.inf` did not work for me because some operations were not well defined.
        # - During the loss computation, in some cases the target sequence cannot be produced at all.
        #   In that case return 0 as the loss (the same behaviour as passing `zero_infinity=True`
        #   to `torch.nn.CTCLoss`).
        # - During development, you can compare your outputs to the outputs of `torch.nn.CTCLoss`
        #   (with `reduction="none"` you can compare individual batch examples; in that case,
        #   the normalization by the target sequence lengths is not performed).  However, in ReCodEx,
        #   `torch.nn.CTCLoss` is not available.
        #neginf = -1e9
        #blank = MorphoDataset.PAD
        log_probs = torch.nn.functional.log_softmax(y_pred, dim=1)
        b, _, tm = log_probs.shape
        input_lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        target_lengths = (y_true != MorphoDataset.PAD).sum(dim=1)
        maxl = y_true.shape[1]
        s = 2 * maxl + 1

        expanded = torch.full((b, s), MorphoDataset.PAD, device=y_pred.device, dtype=torch.long)
        if maxl > 0:
            expanded[:, 1::2] = y_true

        s_idx = torch.arange(s, device=y_pred.device).unsqueeze(0)
        prev2_label = torch.cat([expanded[:, :2], expanded[:, :-2]], dim=1)
        skipok = (expanded != prev2_label) & (s_idx % 2 == 1)
        valid_s = (2 * target_lengths + 1).unsqueeze(1)
        
        alpha = torch.full((b, s), -1e9, device=y_pred.device)
        alpha[:, 0] = log_probs[torch.arange(b, device=y_pred.device), expanded[:, 0], 0]
        if s > 1:
            alpha[:, 1] = log_probs[torch.arange(b, device=y_pred.device), expanded[:, 1], 0]
        
        alpha = torch.where(s_idx < valid_s, alpha, torch.tensor(-1e9, device=y_pred.device))
        
        all_alpha = [alpha]

        for i in range(1, tm):
            prev_0 = alpha
            prev_1 = torch.cat([torch.full((b, 1), -1e9, device=y_pred.device), alpha[:, :-1]], dim=1)
            prev_2 = torch.cat([torch.full((b, 2), -1e9, device=y_pred.device), alpha[:, :-2]], dim=1)
            prev_2 = torch.where(skipok, prev_2, torch.tensor(-1e9, device=y_pred.device))
            
            new_alpha = torch.logsumexp(torch.stack([prev_0, prev_1, prev_2], dim=-1), dim=-1)
            lptn = log_probs[torch.arange(b, device=y_pred.device).unsqueeze(1), expanded, i]
            alpha = new_alpha + lptn
            alpha = torch.where(s_idx < valid_s, alpha, torch.tensor(-1e9, device=y_pred.device))
            all_alpha.append(alpha)

        all_alpha = torch.stack(all_alpha, dim=1)
        tn = (input_lengths - 1).clamp(min=0)
        final_alpha = all_alpha[torch.arange(b, device=y_pred.device), tn]

        finalblank = (2 * target_lengths).clamp(max=s - 1)
        finallabel = (2 * target_lengths - 1).clamp(min=0)
        
        log_p_blank = final_alpha[torch.arange(b, device=y_pred.device), finalblank]
        log_p_label = final_alpha[torch.arange(b, device=y_pred.device), finallabel]
        
        valid_finallabel = target_lengths > 0
        log_p_label = torch.where(valid_finallabel, log_p_label, torch.tensor(-1e9, device=y_pred.device))
        
        log_p = torch.logaddexp(log_p_blank, log_p_label)
        
        lossnorm = -log_p / target_lengths.float().clamp(min=1)
        
        loss = torch.where(log_p <= -1e8, torch.zeros_like(lossnorm), lossnorm)

        return loss.mean()

    def ctc_decoding(self, logits: torch.Tensor, word_ids: torch.Tensor) -> list[torch.Tensor]:
        # TODO: Implement greedy CTC decoding algorithm. The result should be a list of
        # decoded tag sequences, each sequence (batch example) with appropriate length
        # (i.e., at this point we do not pad the predictions in the batch to the same length).
        #
        # The greedy algorithm should, for every batch example:
        # - consider only the predictions corresponding to valid words (i.e., not the padding ones);
        # - compute the most probable extended label for every one of them;
        # - remove repeated labels;
        # - finally remove the blank labels (which are `MorphoDataset.PAD` in our case).
        best = logits.argmax(dim=1)
        input_lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        results = []
        
        for i in range(best.shape[0]):
            seq = best[i, :input_lengths[i]]
            seq = torch.unique_consecutive(seq)
            seq = seq[seq != MorphoDataset.PAD]
            results.append(seq)
            
        return results

    # GOOD
    def compute_metrics(
        self, y_pred: torch.Tensor, y_true: torch.Tensor, word_ids: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        # TODO: Compute predictions using the `ctc_decoding`.
        predictions = self.ctc_decoding(y_pred, word_ids)
        self.metrics["edit_distance"].update(predictions, y_true)
        return self.metrics

    # GOOD
    def predict_step(self, xs):
        with torch.no_grad():
            # Perform constrained decoding.
            yield from self.ctc_decoding(self.forward(*xs), *xs)

# GOOD
def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cnec", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = Dataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = Dataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # We compute the loss using `compute_loss` method, so no `loss` is passed here.
        metrics={"edit_distance": npfl138.metrics.EditDistance(ignore_index=MorphoDataset.PAD),},
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return all metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items()}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)

