#!/usr/bin/env python3
# Made by:
# Jan Benda             465aae63-030f-11eb-9574-ea7484399335
# Veronika Borková      8f7b6d5d-adcc-41af-9ea0-6744c950079e

import argparse

import torch
import torchmetrics

import npfl138
npfl138.require_version("2526.7")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--cle_dim", default=32, type=int, help="CLE embedding dimension.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=64, type=int, help="Word embedding dimension.")
parser.add_argument("--word_masking", default=0.0, type=float, help="Mask words with the given probability.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Model(npfl138.TrainableModule):
    class MaskElements(torch.nn.Module):
        """A layer randomly masking elements with a given value."""
        def __init__(self, mask_probability, mask_value):
            super().__init__()
            self._mask_probability = mask_probability
            self._mask_value = mask_value

        def forward(self, inputs: torch.Tensor) -> torch.Tensor:
            # Only mask during training and when the mask probability is non-zero.
            if self.training and self._mask_probability:
                # DONE: Generate a mask tensor of `torch.float32`s of the same shape
                # as `inputs` using either `torch.rand` or `torch.rand_like`.
                # Then replace the inputs elements whose mask value is less than
                # `self._mask_probability` with the value of `self._mask_value`.
                rand_tensor = torch.rand_like(inputs, dtype=torch.float32)
                mask = (rand_tensor < self._mask_probability) & (inputs != MorphoDataset.PAD)
                inputs[mask] = self._mask_value
            return inputs

    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()

        # Create all needed layers.
        # DONE: Create a word masking layer `self.MaskElements` with the given
        # `args.word_masking` probability and `MorphoDataset.UNK` as the masking value.
        self._word_masking = self.MaskElements(args.word_masking, MorphoDataset.UNK)

        # DONE: Create a `torch.nn.Embedding` layer for embedding the character ids
        # from `train.words.char_vocab` to dimensionality `args.cle_dim`.
        self._char_embedding = torch.nn.Embedding(len(train.words.char_vocab), args.cle_dim)

        # DONE: Create a bidirectional `torch.nn.GRU` layer processing the character
        # embeddings, producing output of dimensionality `args.cle_dim`.
        self._char_rnn = torch.nn.GRU(args.cle_dim, args.cle_dim, bidirectional=True, batch_first=True)

        self._word_embedding = torch.nn.Embedding(num_embeddings=len(train.words.string_vocab), embedding_dim=args.we_dim)


        # DONE: Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # **now concatenated with the character-level embeddings**, and we will sum
        # the forward and backward outputs.
        if args.rnn == "LSTM":
            self._word_rnn = torch.nn.LSTM(args.we_dim + 2*args.cle_dim, args.rnn_dim, bidirectional=True, batch_first=True)
        else:
            self._word_rnn = torch.nn.GRU(args.we_dim + 2*args.cle_dim, args.rnn_dim, bidirectional=True, batch_first=True)

        self._output_layer = torch.nn.Linear(args.rnn_dim, len(train.tags.string_vocab))


    def forward(self, word_ids: torch.Tensor, unique_words: torch.Tensor, word_indices: torch.Tensor) -> torch.Tensor:
        # DONE: Mask the input `word_ids` using the `self._word_masking` layer.
        hidden = self._word_masking(word_ids)

        # DONE: Embed the masked word IDs in `hidden` using the word embedding layer.
        hidden = self._word_embedding(hidden)

        # DONE: Embed the `unique_words` using the character embedding layer.
        cle = self._char_embedding(unique_words)

        # DONE: Pass the character embeddings through the character-level RNN.
        # As during word-level RNN, start by packing the input sequence.
        lengths = (unique_words != MorphoDataset.PAD).sum(dim=1)
        packed = torch.nn.utils.rnn.pack_padded_sequence(cle, lengths.cpu(), batch_first=True, enforce_sorted=False)
        

        # DONE: Pass the `PackedSequence` through the character RNN, obtaining fixed-size
        # representation of every unique word in the batch. Then, concatenate the states
        # of the forward and backward directions (in this order).
        packed, states = self._char_rnn(packed)
        cle = torch.cat([states[0], states[1]], dim=1)

        # DONE: With `cle` being the character-level embeddings of the unique words
        # of shape `[num_unique_words, 2 * cle_dim]`, create the representation of the
        # (not necessary unique) sentence words by indexing the character-level
        # embeddings with the `word_indices`. The result should have a shape
        # `[batch_size, max_sentence_length, 2 * cle_dim]`. You can use for example
        # the `torch.nn.functional.embedding` function.
        cle = torch.nn.functional.embedding(word_indices, cle, padding_idx=MorphoDataset.PAD)

        # DONE: Concatenate the word embeddings with the character-level embeddings (in this order).
        hidden = torch.cat([hidden, cle], dim=2)

        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        packed = torch.nn.utils.rnn.pack_padded_sequence(hidden, lengths.cpu(), batch_first=True, enforce_sorted=False)
        packed = self._word_rnn(packed)[0]
        hidden = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)[0]
        half_width = hidden.size(2)//2
        hidden = hidden[:,:,:half_width] + hidden[:,:,half_width:]
        hidden = self._output_layer(hidden)
        hidden = hidden.moveaxis(1,2)

        return hidden


class TrainableDataset(npfl138.TransformedDataset):
    def transform(self, example):
        word_ids = torch.tensor([self.dataset.words.string_vocab.index(word) for word in example['words']])
        tag_ids = torch.tensor([self.dataset.tags.string_vocab.index(tag) for tag in example['tags']])
        # Note that compared to `tagger_we`, we also return the original
        # words in order to be able to compute the character-level embeddings.
        return word_ids, example["words"], tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, words, tag_ids = zip(*batch)
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True)

        # DONE: Create required inputs for the character-level embeddings using
        # the provided `self.dataset.cle_batch` function on `words`. The function
        # returns a pair of two PyTorch tensors:
        # - `unique_words` with shape `[num_unique_words, max_word_length]` containing
        #   each unique word as a sequence of character ids,
        # - `words_indices` with shape `[num_sentences, max_sentence_length]`
        #   containing for every word its index in `unique_words`.
        unique_words, words_indices = self.dataset.cle_batch(words)

        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True)
        return (word_ids, unique_words, words_indices), tag_ids


def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads, args.recodex)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cac", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = TrainableDataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        optimizer=torch.optim.Adam(model.parameters()),
        loss=torch.nn.CrossEntropyLoss(ignore_index=morpho.PAD),
        metrics={"accuracy": torchmetrics.Accuracy(
            task="multiclass",
            num_classes=len(morpho.train.tags.string_vocab),
            ignore_index=morpho.PAD)},
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return development metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items() if metric.startswith("dev:")}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
