#!/usr/bin/env python3
# Made by:
# Jan Benda             465aae63-030f-11eb-9574-ea7484399335
# Veronika Borková      8f7b6d5d-adcc-41af-9ea0-6744c950079e

#!/usr/bin/env python3
import argparse
import os

import torch
import torchmetrics

from torch.utils.data import Subset

import npfl138
npfl138.require_version("2526.7")
from npfl138.datasets.morpho_dataset import MorphoDataset
from npfl138.datasets.morpho_analyzer import MorphoAnalyzer


# TODO: Define reasonable defaults and optionally more parameters.
# Also, you can set the number of threads to 0 to use all your CPU cores.
parser = argparse.ArgumentParser()
parser.add_argument("--batch_size", default=64, type=int, help="Batch size.")
parser.add_argument("--epochs", default=40, type=int, help="Number of epochs.")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")

parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=128, type=int, help="RNN layer dimension.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
parser.add_argument("--word_masking", default=0.3, type=float, help="Mask words with the given probability.")
parser.add_argument("--cle_dim", default=64, type=int, help="CLE embedding dimension.")
parser.add_argument("--num_layers", default=2, type=int, help="Number of RNN layers.")

class Model(npfl138.TrainableModule):
    class MaskElements(torch.nn.Module):
        """A layer randomly masking elements with a given value."""
        def __init__(self, mask_probability, mask_value):
            super().__init__()
            self._mask_probability = mask_probability
            self._mask_value = mask_value

        def forward(self, inputs: torch.Tensor) -> torch.Tensor:
            # Only mask during training and when the mask probability is non-zero.
            if self.training and self._mask_probability:
                # DONE: Generate a mask tensor of `torch.float32`s of the same shape
                # as `inputs` using either `torch.rand` or `torch.rand_like`.
                # Then replace the inputs elements whose mask value is less than
                # `self._mask_probability` with the value of `self._mask_value`.
                rand_tensor = torch.rand_like(inputs, dtype=torch.float32)
                mask = (rand_tensor < self._mask_probability) & (inputs != MorphoDataset.PAD)
                inputs[mask] = self._mask_value
            return inputs

    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset, class_sizes) -> None:
        super().__init__()

        # Create all needed layers.
        # Create a word masking layer `self.MaskElements` with the given
        # `args.word_masking` probability and `MorphoDataset.UNK` as the masking value.
        self._word_masking = self.MaskElements(args.word_masking, MorphoDataset.UNK)

        # Create a `torch.nn.Embedding` layer for embedding the character ids
        # from `train.words.char_vocab` to dimensionality `args.cle_dim`.
        self._char_embedding = torch.nn.Embedding(len(train.words.char_vocab), args.cle_dim)

        # Create a bidirectional `torch.nn.GRU` layer processing the character
        # embeddings, producing output of dimensionality `args.cle_dim`.
        self._char_rnn = torch.nn.GRU(args.cle_dim, args.cle_dim, bidirectional=True, batch_first=True)

        self._word_embedding = torch.nn.Embedding(num_embeddings=len(train.words.string_vocab), embedding_dim=args.we_dim)


        # Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # **now summed with the character-level embeddings**, and we will sum
        # the forward and backward outputs.
        if args.rnn == "LSTM":
            self._word_rnn = torch.nn.LSTM(args.we_dim, args.rnn_dim, num_layers=args.num_layers, bidirectional=True, batch_first=True)
        else:
            self._word_rnn = torch.nn.GRU(args.we_dim, args.rnn_dim, bidirectional=True, batch_first=True)

        self._output_layers = torch.nn.ModuleList(torch.nn.Linear(args.rnn_dim, class_size) for class_size in class_sizes) 

    def forward(self, word_ids: torch.Tensor, unique_words: torch.Tensor, word_indices: torch.Tensor) -> torch.Tensor:
        # Mask the input `word_ids` using the `self._word_masking` layer.
        hidden = self._word_masking(word_ids)

        # Embed the masked word IDs in `hidden` using the word embedding layer.
        hidden = self._word_embedding(hidden)

        # Embed the `unique_words` using the character embedding layer.
        cle = self._char_embedding(unique_words)

        # Pass the character embeddings through the character-level RNN.
        # As during word-level RNN, start by packing the input sequence.
        lengths = (unique_words != MorphoDataset.PAD).sum(dim=1)
        packed = torch.nn.utils.rnn.pack_padded_sequence(cle, lengths.cpu(), batch_first=True, enforce_sorted=False)
        
        # Pass the `PackedSequence` through the character RNN, obtaining fixed-size
        # representation of every unique word in the batch. Then, concatenate the states
        # of the forward and backward directions (in this order).
        packed, states = self._char_rnn(packed)
        cle = torch.cat([states[0], states[1]], dim=1)

        # With `cle` being the character-level embeddings of the unique words
        # of shape `[num_unique_words, 2 * cle_dim]`, create the representation of the
        # (not necessary unique) sentence words by indexing the character-level
        # embeddings with the `word_indices`. The result should have a shape
        # `[batch_size, max_sentence_length, 2 * cle_dim]`. You can use for example
        # the `torch.nn.functional.embedding` function.
        cle = torch.nn.functional.embedding(word_indices, cle, padding_idx=MorphoDataset.PAD)

        # DONE: Sum the word embeddings with the character-level embeddings (in this order).
        hidden = hidden + cle

        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        packed = torch.nn.utils.rnn.pack_padded_sequence(hidden, lengths.cpu(), batch_first=True, enforce_sorted=False)
        packed = self._word_rnn(packed)[0]
        hidden = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)[0]
        half_width = hidden.size(2)//2
        hidden = hidden[:,:,:half_width] + hidden[:,:,half_width:]
        outputs = [head(hidden).moveaxis(1,2) for head in self._output_layers]

        return outputs

    def compute_loss(self, predictions, targets, *inputs):
        loss = torch.nn.CrossEntropyLoss(ignore_index=MorphoDataset.PAD)
        total_loss = 0
        for i in range(15):
            total_loss += loss(predictions[i], targets[:,:,i])
        return total_loss




class TrainableDataset(npfl138.TransformedDataset):
    def __init__(self, dataset, classes):
        super().__init__(dataset)
        self.classes = classes

    def transform(self, example):
        word_ids = torch.tensor([self.dataset.words.string_vocab.index(word) for word in example['words']])
        tag_ids = torch.zeros((len(example['tags']), 15), dtype=int)
        for i in range(len(example['tags'])):
            tag = example['tags'][i]
            for j in range(15):
                if len(tag)==15:
                    if tag[j] in self.classes[j]:
                        tag_ids[i,j] = self.classes[j].index(tag[j])
                    else:
                        # print(tag, example)
                        tag_ids[i,j] = 0

                else:
                    # print(tag, example)
                    tag_ids[i,j] = 0


        # Note that compared to `tagger_we`, we also return the original
        # words in order to be able to compute the character-level embeddings.
        return word_ids, example["words"], tag_ids
    

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, words, tag_ids = zip(*batch)
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True)

        # DONE: Create required inputs for the character-level embeddings using
        # the provided `self.dataset.cle_batch` function on `words`. The function
        # returns a pair of two PyTorch tensors:
        # - `unique_words` with shape `[num_unique_words, max_word_length]` containing
        #   each unique word as a sequence of character ids,
        # - `words_indices` with shape `[num_sentences, max_sentence_length]`
        #   containing for every word its index in `unique_words`.
        unique_words, words_indices = self.dataset.cle_batch(words)

        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True)
        return (word_ids, unique_words, words_indices), tag_ids




def main(args: argparse.Namespace) -> None:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Create a suitable logdir for the logs and the predictions.
    logdir = npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args))

    # Load the data. Using analyses is only optional.
    morpho = MorphoDataset("czech_pdt")
    analyses = MorphoAnalyzer("czech_pdt_analyses")


    pad = morpho.PAD
    classes = [['PAD'] for _ in range(15)]
    for sentence in morpho.train:
        for tag in sentence['tags']:
            for i in range(15):
                if tag[i] not in classes[i]:
                    classes[i].append(tag[i])
    classes_size = [len(c) for c in classes]

    train = TrainableDataset(morpho.train, classes).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = TrainableDataset(morpho.dev, classes).dataloader(batch_size=args.batch_size)
    test = TrainableDataset(morpho.test, classes).dataloader(batch_size=args.batch_size)






    model =  Model(args, morpho.train, classes_size)

    model.configure(
        optimizer=torch.optim.Adam(model.parameters()),
        metrics={},
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)


    # Generate test set annotations, but in `logdir` to allow parallel execution.
    os.makedirs(logdir, exist_ok=True)
    with open(os.path.join(logdir, "tagger_competition.txt"), "w", encoding="utf-8") as predictions_file:
        # TODO: Predict the tags on the test set. The following code assumes you use the same
        # output structure as in `tagger_we`, i.e., that for each sentence, the predictions are
        # a Numpy vector of shape `[num_tags, sentence_len_or_more]`, where `sentence_len_or_more`
        # is the length of the corresponding batch. (FYI, if you instead used the `packed` variant,
        # the prediction for each sentence is a vector of shape `[exactly_sentence_len, num_tags]`.)
        predictions = model.predict(test, data_with_labels=True, as_numpy=True)


        final_tags = []
        for words, prediction in zip(morpho.test.words.strings, predictions):
            pred_tags = []
            tag_ids = torch.zeros((len(prediction[0][0]), 15), dtype=int)
            for i in range(15):
                tag_ids[:,i] = torch.tensor(prediction[i]).argmax(dim=0)
            for i in range(len(words)):
                tag_list = [classes[j][tag_ids[i,j]] for j in range(15)]
                pred_tags.append("".join(tag_list))
            final_tags.append(pred_tags)


        # for predicted_tags, words in zip(predictions, morpho.test.words.strings):

        #     for predicted_tag in predicted_tags[:, :len(words)].argmax(axis=0):
        #         print(morpho.train.tags.string_vocab.string(predicted_tag), file=predictions_file)
        #         print(morpho.train.tags.string_vocab.string(predicted_tag))
        #     print(file=predictions_file)

        for final_tag_set in final_tags:
            for tag in final_tag_set:
                print(tag, file=predictions_file)
            print(file=predictions_file)


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
